apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wikijs-exer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs
        image: requarks/wiki:latest
        env:
        - name: DB_TYPE
          value: "postgres"
        - name: DB_HOST
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "wikijs_user"
        - name: DB_PASS
          value: "your_db_password"  # Vul in met je database wachtwoord
        - name: DB_NAME
          value: "wikijs"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: wikijs-exer
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: wikijs
