apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wiki-tls-secret
spec:
  secretName: wiki-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wiki.cloudops-xx.ucll.cloud
  dnsNames:
  - wiki.cloudops-xx.ucll.cloud
